2024-04-29 17:07:12,251 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-29 17:07:12,252 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Configure stats pid to 42326
2024-04-29 17:07:12,252 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Loading settings from /home/hghallab/.config/wandb/settings
2024-04-29 17:07:12,252 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Loading settings from /home/hghallab/Dvlp/GANs/HDCGAN/wandb/settings
2024-04-29 17:07:12,252 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-29 17:07:12,252 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-29 17:07:12,252 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-29 17:07:12,252 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-29 17:07:12,252 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-29 17:07:12,252 INFO    MainThread:42326 [wandb_init.py:_log_setup():521] Logging user logs to /home/hghallab/Dvlp/GANs/DCGAN/wandb/run-20240429_170712-6wy0nv9v/logs/debug.log
2024-04-29 17:07:12,252 INFO    MainThread:42326 [wandb_init.py:_log_setup():522] Logging internal logs to /home/hghallab/Dvlp/GANs/DCGAN/wandb/run-20240429_170712-6wy0nv9v/logs/debug-internal.log
2024-04-29 17:07:12,252 INFO    MainThread:42326 [wandb_init.py:_jupyter_setup():467] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x716ae489e410>
2024-04-29 17:07:12,252 INFO    MainThread:42326 [wandb_init.py:init():561] calling init triggers
2024-04-29 17:07:12,252 INFO    MainThread:42326 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'seed': 12, 'debug': False, 'model_name': 'HDCGAN|OneImageSet', 'loss_function': 'BCELoss', 'train_bs': 8, 'valid_bs': 8, 'img_size': [512, 512], 'epochs': 500, 'lr': 0.0002, 'n_accumulate': 4, 'device': device(type='cpu')}
2024-04-29 17:07:12,253 INFO    MainThread:42326 [wandb_init.py:init():611] starting backend
2024-04-29 17:07:12,253 INFO    MainThread:42326 [wandb_init.py:init():615] setting up manager
2024-04-29 17:07:12,255 INFO    MainThread:42326 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-29 17:07:12,257 INFO    MainThread:42326 [wandb_init.py:init():623] backend started and connected
2024-04-29 17:07:12,262 INFO    MainThread:42326 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-29 17:07:12,262 INFO    MainThread:42326 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-29 17:07:12,262 INFO    MainThread:42326 [wandb_init.py:init():715] updated telemetry
2024-04-29 17:07:12,276 INFO    MainThread:42326 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-29 17:07:12,916 INFO    MainThread:42326 [wandb_run.py:_on_init():2357] communicating current version
2024-04-29 17:07:13,073 INFO    MainThread:42326 [wandb_run.py:_on_init():2366] got version response 
2024-04-29 17:07:13,073 INFO    MainThread:42326 [wandb_init.py:init():799] starting run threads in backend
2024-04-29 17:07:13,428 INFO    MainThread:42326 [wandb_run.py:_console_start():2335] atexit reg
2024-04-29 17:07:13,428 INFO    MainThread:42326 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-04-29 17:07:13,428 INFO    MainThread:42326 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-04-29 17:07:13,429 INFO    MainThread:42326 [wandb_run.py:_redirect():2280] Redirects installed.
2024-04-29 17:07:13,429 INFO    MainThread:42326 [wandb_init.py:init():842] run started, returning control to user process
2024-04-29 17:07:13,429 INFO    MainThread:42326 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-29 17:07:13,429 INFO    MainThread:42326 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-29 17:07:17,970 INFO    MainThread:42326 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-29 17:07:17,984 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-29 17:07:17,984 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Configure stats pid to 42326
2024-04-29 17:07:17,984 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Loading settings from /home/hghallab/.config/wandb/settings
2024-04-29 17:07:17,984 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Loading settings from /home/hghallab/Dvlp/GANs/HDCGAN/wandb/settings
2024-04-29 17:07:17,985 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-29 17:07:17,985 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-29 17:07:17,985 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-29 17:07:17,985 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-29 17:07:17,986 INFO    MainThread:42326 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-29 17:07:17,986 INFO    MainThread:42326 [wandb_init.py:_log_setup():521] Logging user logs to /home/hghallab/Dvlp/GANs/DCGAN/wandb/run-20240429_170717-lup4h2yy/logs/debug.log
2024-04-29 17:07:17,986 INFO    MainThread:42326 [wandb_init.py:_log_setup():522] Logging internal logs to /home/hghallab/Dvlp/GANs/DCGAN/wandb/run-20240429_170717-lup4h2yy/logs/debug-internal.log
2024-04-29 17:07:17,986 INFO    MainThread:42326 [wandb_init.py:init():561] calling init triggers
2024-04-29 17:07:17,987 INFO    MainThread:42326 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'seed': 12, 'debug': False, 'model_name': 'HDCGAN|OneImageSet', 'loss_function': 'BCELoss', 'train_bs': 8, 'valid_bs': 8, 'img_size': [512, 512], 'epochs': 500, 'lr': 0.0002, 'n_accumulate': 4, 'device': device(type='cpu')}
2024-04-29 17:07:17,987 INFO    MainThread:42326 [wandb_init.py:init():586] re-initializing run, found existing run on stack: 6wy0nv9v
2024-04-29 17:07:17,989 INFO    MainThread:42326 [wandb_run.py:_finish():2064] finishing run houda222/HDCGAN/6wy0nv9v
2024-04-29 17:07:17,989 ERROR   MainThread:42326 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-04-29 17:07:17,990 INFO    MainThread:42326 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-29 17:07:17,990 INFO    MainThread:42326 [wandb_init.py:_jupyter_teardown():449] cleaning up jupyter logic
2024-04-29 17:07:17,990 INFO    MainThread:42326 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-04-29 17:07:17,990 INFO    MainThread:42326 [wandb_run.py:_restore():2287] restore
2024-04-29 17:07:17,991 INFO    MainThread:42326 [wandb_run.py:_restore():2293] restore done
2024-04-29 17:07:20,938 INFO    MainThread:42326 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-04-29 17:07:20,939 INFO    MainThread:42326 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-04-29 17:07:20,942 INFO    MainThread:42326 [wandb_run.py:_footer_sync_info():3895] logging synced files
